Replace eval_gap by run_gap, and use that in more places
Basically, we drop the `eval` from `eval_gap` and rename the function to
`run_gap`. That allows us to use it in further spots, and thus benefit
from the extended error handling it performs.

diff --git a/release b/release
--- a/release
+++ b/release
@@ -94,23 +94,22 @@ verify_git_clean() {
         error "uncommitted changes detected"
 }
 
-# execute GAP commands from a heredoc, and evaluate the result,
-# unless GAP reported any errors
-eval_gap() {
+# execute GAP commands from a heredoc, and export its output in the shell
+# variable `gap_output`; abort if GAP reported any errors
+run_gap() {
   # Invoke GAP. The final call to 'tr' removes newlines and is a workaround
   # for people whose gap script is broken (by not honoring -A, thus loading
   # Browse, which inserts that extra character). I am looking at you,
   # Sebastian!
-  output=$( \
+  gap_output=$( \
     (echo 'OnBreak:=function() Print("FATAL ERROR"); FORCE_QUIT_GAP(1); end;;' ; cat - ; echo ; echo "FORCE_QUIT_GAP(0);") \
     | $GAP -A -q -b 2>&1 \
     | tr -d '\r' )
   mkdir -p "$TMP_DIR"
-  echo "$output" > "$TMP_DIR/gap-error.log"
-  if echo "$output" | grep -q '\(Error\|FATAL ERROR\|Syntax \)' ; then
+  echo "$gap_output" > "$TMP_DIR/gap-error.log"
+  if echo "$gap_output" | grep -q '\(Error\|FATAL ERROR\|Syntax \)' ; then
     error "there was an error running GAP, see $TMP_DIR/gap-error.log"
   fi
-  eval "$output"
 }
 
 # helper function for parsing GitHub's JSON output. Right now,
@@ -208,7 +207,7 @@ verify_git_clean
 # Determine package name and version, and other meta data
 #
 notice "Extracting information from PackageInfo.g..."
-eval_gap <<EOF
+run_gap <<EOF
 Read("PackageInfo.g");
 Print("PKG=\"",GAPInfo.PackageInfoCurrent.PackageName,"\"\n");
 Print("VERSION=\"",GAPInfo.PackageInfoCurrent.Version,"\"\n");
@@ -233,12 +232,13 @@ else
 fi;
 EOF
 
-notice "Package $PKG $VERSION"
-
+# evaluate the output of GAP, which should be valid shell script code
+eval "$gap_output"
 if [ x"$GAP_ERROR" != "x" ] ; then
     error "$GAP_ERROR"
 fi
 
+notice "Package $PKG $VERSION"
 case "$VERSION" in
   *dev) error "Must not use 'dev' versions for package releases" ;;
 esac
@@ -251,12 +251,11 @@ esac
 #
 if [ -f makedoc.g ] ; then
     notice "Building GAP package documentation (using makedoc.g)"
-    $GAP -A -q <<GAPInput
+    run_gap <<GAPInput
 if not IsPackageMarkedForLoading("$PKG", "") then
   SetPackagePath("$PKG", ".");
 fi;
 Read("makedoc.g");
-FORCE_QUIT_GAP(0);
 GAPInput
 elif [ -f doc/make_doc ] ; then
     notice "Building GAP package documentation (using doc/make_doc)"
@@ -399,13 +398,12 @@ fi
 
 if [ -f makedoc.g ] ; then
     notice "Building GAP package documentation for archives (using makedoc.g)"
-    $GAP -A -q <<GAPInput
+    run_gap <<GAPInput
 if not IsPackageMarkedForLoading("$PKG", "") then
   SetPackagePath("$PKG", ".");
 fi;
 PushOptions(rec(relativePath:="../../.."));
 Read("makedoc.g");
-FORCE_QUIT_GAP(0);
 GAPInput
     rm -f doc/*.lab doc/*.tex
     rm -f doc/*.aux doc/*.bbl doc/*.blg doc/*.brf doc/*.idx doc/*.ilg doc/*.ind doc/*.log doc/*.out doc/*.pnr doc/*.tst
@@ -430,11 +428,10 @@ fgrep -q -r '<a href="/' */*.htm* &&
 #
 echo ""
 notice "Validating PackageInfo.g..."
-$GAP -A -q <<GAPInput || error "validation failed"
+run_gap <<GAPInput || error "validation failed"
 if not ValidatePackageInfo("PackageInfo.g") then
     FORCE_QUIT_GAP(1);
 fi;
-FORCE_QUIT_GAP(0);
 GAPInput
 
 
@@ -602,9 +599,8 @@ for f in ./*/*.htm* ; do
   mv "$f.bak" "$f"
 done
 
-$GAP -A -q <<GAPInput
+run_gap <<GAPInput
 Read("update.g");
-FORCE_QUIT_GAP(0);
 GAPInput
 
 git add -A .
