error out if curl is not available

diff --git a/release b/release
--- a/release
+++ b/release
@@ -78,6 +78,10 @@ if [ ! -f PackageInfo.g ] ; then
     error "unable to read PackageInfo.g file, use --help for instructions"
 fi
 
+if ! command -v curl >/dev/null 2>&1 ; then
+    error "the 'curl' command was not found, please install it"
+fi
+
 ######################################################################
 #
 # Command line processing
